config/routes.rb
KopfsacheStulln::Application.routes.draw do

  root 'home#index'
  get 'impressum.html' => 'home#impressum', as: 'impressum'
  get 'team.html' => 'home#team', as: 'team'
  get 'kontakt.html' => 'home#kontakt', as: 'kontakt'
  get 'salon.html' => 'home#salon', as: 'salon'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def impressum
    render :impressum
  end

  def team
    render :team
  end

  def salon
    render :salon
  end

  def service
    render :service
  end
end

app/views/home/impressum.html.erb
<% content_for(:title) do %>Impressum<% end %>
<div class="container container-panorama-header container-sidepages impressum">

</div>
<div class="container container-main">

  <div class="row">
    <div class="col-md-10 col-md-offset-2">
      <h1 class="sidepage">Impressum</h1>

      <p>Angaben gemäß § 5 TMG</p>
      <p>Kopfsache Stulln <br>
        Kirchstr. 5<br>
        92551 Stulln <br>
      </p><p> <strong>Vertreten durch: </strong><br>
        Andrea Kraus<br>
      </p><p><strong>Kontakt:</strong> <br>
        Telefon: 09435 30 02 32<br>
        </p>

      <p><strong>Umsatzsteuer-ID: </strong> <br>
        Umsatzsteuer-Identifikationsnummer gemäß §27a Umsatzsteuergesetz: DE251401296<br><br>

      </p>

      <p><strong>Haftungsausschluss: </strong><br><br>
        <strong>Haftung für Inhalte</strong><br><br>
        Die Inhalte unserer Seiten wurden mit größter Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte können wir jedoch keine Gewähr übernehmen. Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.<br><br><strong>Haftung für Links</strong><br><br>
        Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.<br><br><strong>Urheberrecht</strong><br><br>
        Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.<br><br><strong>Datenschutz</strong><br><br>
        Die Nutzung unserer Webseite ist in der Regel ohne Angabe personenbezogener Daten möglich. Soweit auf unseren Seiten personenbezogene Daten (beispielsweise Name, Anschrift oder eMail-Adressen) erhoben werden, erfolgt dies, soweit möglich, stets auf freiwilliger Basis. Diese Daten werden ohne Ihre ausdrückliche Zustimmung nicht an Dritte weitergegeben. <br>
        Wir weisen darauf hin, dass die Datenübertragung im Internet (z.B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich. <br>
        Der Nutzung von im Rahmen der Impressumspflicht veröffentlichten Kontaktdaten durch Dritte zur Übersendung von nicht ausdrücklich angeforderter Werbung und Informationsmaterialien wird hiermit ausdrücklich widersprochen. Die Betreiber der Seiten behalten sich ausdrücklich rechtliche Schritte im Falle der unverlangten Zusendung von Werbeinformationen, etwa durch Spam-Mails, vor.<br>
        <br><br><strong>Google Analytics</strong><br><br>
        Diese Website benutzt Google Analytics, einen Webanalysedienst der Google Inc. (''Google''). Google Analytics verwendet sog. ''Cookies'', Textdateien, die auf Ihrem Computer gespeichert werden und die eine Analyse der Benutzung der Website durch Sie ermöglicht. Die durch den Cookie erzeugten Informationen über Ihre Benutzung diese Website (einschließlich Ihrer IP-Adresse) wird an einen Server von Google in den USA übertragen und dort gespeichert. Google wird diese Informationen benutzen, um Ihre Nutzung der Website auszuwerten, um Reports über die Websiteaktivitäten für die Websitebetreiber zusammenzustellen und um weitere mit der Websitenutzung und der Internetnutzung verbundene Dienstleistungen zu erbringen. Auch wird Google diese Informationen gegebenenfalls an Dritte übertragen, sofern dies gesetzlich vorgeschrieben oder soweit Dritte diese Daten im Auftrag von Google verarbeiten. Google wird in keinem Fall Ihre IP-Adresse mit anderen Daten der Google in Verbindung bringen. Sie können die Installation der Cookies durch eine entsprechende Einstellung Ihrer Browser Software verhindern; wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht sämtliche Funktionen dieser Website voll umfänglich nutzen können. Durch die Nutzung dieser Website erklären Sie sich mit der Bearbeitung der über Sie erhobenen Daten durch Google in der zuvor beschriebenen Art und Weise und zu dem zuvor benannten Zweck einverstanden.</p><br>
        Website Impressum erstellt durch <a href="http://www.impressum-generator.de" target="impressum-generator">impressum-generator.de</a>


    </div>
  </div>


</div>

app/views/home/index.html.erb
<div class="container container-panorama-header">

  <div class="fullwidthbanner-container">
    <div class="fullwidthbanner" style="overflow: hidden">
      <ul>
        <li data-transition="fade" data-slotamount="10" data-masterspeed="300" data-thumb="images/thumbs/thumb1.jpg">
          <img src="<%= asset_path("panorama2.jpg") %>" data-fullwidthcentering="on">
        </li>

        <li data-transition="fade" data-slotamount="0" data-masterspeed="2300" data-delay="9400" data-thumb="images/thumbs/thumb2.jpg">
          <img src="<%= asset_path("panorama1.jpg") %>" data-fullwidthcentering="on">
        </li>

        <li data-transition="fade" data-slotamount="2" data-masterspeed="2300" data-delay="9400">
          <img src="<%= asset_path("panorama3.jpg") %>" data-fullwidthcentering="on">
        </li>
      </ul>

      <div class="tp-bannertimer"></div>

    </div>
  </div>
</div>

<div class="container container-main">
  <div class="row">
    <div class="col-md-8">
      <div class="panel-box">
          <h3 class="panel-header"><i class="fa fa-cut"></i> Frisör Kopfsache</h3>
        <p>Herzlich Willkommen bei Kopfsache by Andrea Kraus - wir zaubern Wohlfühlmomente für ihr Haar - seit fast 10 Jahren.</p>

        <p>Vereinbaren Sie direkt einen Termin (<abbr title="Telefon"><i class="fa fa-phone"></i></abbr> <a href="tel:00499435300232">09435 30 02 32</a>) und besuchen Sie uns in Stulln (<%= link_to "Kirchstr. 5", kontakt_path %>).</p>
        <p>Wir freuen uns auf ihren Besuch und ihre Wünsche erfüllen zu dürfen</p>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel-box">
        <h3 class="panel-header"><i class="fa fa-clock-o"></i> Öffnungszeiten</h3>
        <dl class="dl-horizontal">
          <dt>Montag, Dienstag</dt>
          <dd>8-19 Uhr</dd>
          <dt>Mittwoch</dt>
          <dd>8-13 Uhr</dd>
          <dt>Donnerstag</dt>
          <dd>geschlossen</dd>
          <dt>Freitag</dt>
          <dd>8-19 Uhr</dd>
          <dt>Samstag</dt>
          <dd>8-13 Uhr</dd>
        </dl>
      </div>
    </div>
  </div>
</div>

</div>
<script type="text/javascript">

    var tpj=jQuery;
    tpj.noConflict();

    tpj(document).ready(function() {

        if (tpj.fn.cssOriginal!=undefined)
            tpj.fn.css = tpj.fn.cssOriginal;

        var slider = tpj('.fullwidthbanner').revolution(
                {
                    delay:9000,
                    startwidth:960,
                    startheight:500,

                    onHoverStop:"on",						// Stop Banner Timet at Hover on Slide on/off

                    thumbWidth:100,							// Thumb With and Height and Amount (only if navigation Tyope set to thumb !)
                    thumbHeight:50,
                    thumbAmount:3,

                    hideThumbs:0,
                    navigationType:"bullet",				// bullet, thumb, none
                    navigationArrows:"solo",				// nexttobullets, solo (old name verticalcentered), none

                    navigationStyle:"round",				// round,square,navbar,round-old,square-old,navbar-old, or any from the list in the docu (choose between 50+ different item), custom


                    navigationHAlign:"center",				// Vertical Align top,center,bottom
                    navigationVAlign:"bottom",					// Horizontal Align left,center,right
                    navigationHOffset:0,
                    navigationVOffset:20,

                    soloArrowLeftHalign:"left",
                    soloArrowLeftValign:"center",
                    soloArrowLeftHOffset:20,
                    soloArrowLeftVOffset:0,

                    soloArrowRightHalign:"right",
                    soloArrowRightValign:"center",
                    soloArrowRightHOffset:20,
                    soloArrowRightVOffset:0,

                    touchenabled:"on",						// Enable Swipe Function : on/off



                    stopAtSlide:-1,							// Stop Timer if Slide "x" has been Reached. If stopAfterLoops set to 0, then it stops already in the first Loop at slide X which defined. -1 means do not stop at any slide. stopAfterLoops has no sinn in this case.
                    stopAfterLoops:-1,						// Stop Timer if All slides has been played "x" times. IT will stop at THe slide which is defined via stopAtSlide:x, if set to -1 slide never stop automatic

                    hideCaptionAtLimit:0,					// It Defines if a caption should be shown under a Screen Resolution ( Basod on The Width of Browser)
                    hideAllCaptionAtLilmit:0,				// Hide all The Captions if Width of Browser is less then this value
                    hideSliderAtLimit:0,					// Hide the whole slider, and stop also functions if Width of Browser is less than this value


                    fullWidth:"on",

                    shadow:0								//0 = no Shadow, 1,2,3 = 3 Different Art of Shadows -  (No Shadow in Fullwidth Version !)

                });
        slider.bind("revolution.slide.onloaded",function (e,data) {
            jQuery('.tp-bannertimer').before('<div class="orbit-bigbar"></div>');
            jQuery('.tp-bannertimer').before('<div class="orbit-bigbar-logo"><%= image_tag("kopfsache-logo-glass.png") %></div>');
        });
    });
</script>

app/views/home/kontakt.html.erb
<% content_for(:title) do %>Kontakt<% end %>
<div class="container container-panorama-header container-sidepages kontakt">
  <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.de/maps?q=kirchstra%C3%9Fe+5,+92551+stulln&amp;ie=UTF8&amp;oe=utf-8&amp;hnear=Kirchstra%C3%9Fe+5,+92551+Stulln&amp;t=m&amp;hq=&amp;ll=49.421164,12.140751&amp;spn=0.009771,0.051498&amp;z=15&amp;output=embed"></iframe>
</div>
<div class="container container-main">

  <div class="row">
    <div class="col-md-10 col-md-offset-2">
      <h1 class="sidepages">Kontakt</h1>
      <address>
        <strong>Kopfsache by Andrea Kraus</strong><br>
        Kirchstr. 5<br>
        92551 Stulln<br><br>
        <abbr title="Telefon"><i class="fa fa-phone"></i></abbr> <a href="tel:00499435300232">09435 30 02 32</a>
      </address>
    </div>
  </div>

</div>

app/views/home/salon.html.erb
<% content_for(:title) do %>Salon und Service<% end %>
<div class="container container-panorama-salon">

  <div class="fullwidthbanner-container">
    <div class="fullwidthbanner" style="overflow: hidden">
      <ul>
        <li data-transition="fade" data-slotamount="10" data-masterspeed="300" data-thumb="images/thumbs/thumb1.jpg">
          <img src="<%= asset_path("panorama2.jpg") %>" data-fullwidthcentering="on">
        </li>

        <li data-transition="fade" data-slotamount="0" data-masterspeed="2300" data-delay="9400" data-thumb="images/thumbs/thumb2.jpg">
          <img src="<%= asset_path("panorama1.jpg") %>" data-fullwidthcentering="on">
        </li>

        <li data-transition="fade" data-slotamount="2" data-masterspeed="2300" data-delay="9400"">
          <img src="<%= asset_path("panorama3.jpg") %>" data-fullwidthcentering="on">
        </li>
      </ul>

      <div class="tp-bannertimer"></div>
    </div>
  </div>
</div>
<div class="container container-main">
  <h1 class="sidepages">Salon</h1>
  <div class="row padding-bottom">
    <div class="col-md-6">
      <h2>Wir für Sie</h2>
      <ul class="list-unstyled">
        <li>3x wöchentlich bis 19 Uhr geöffnet</li>
        <li>Telefonische Terminvereinbarung für kurze Wartezeiten</li>
        <li>Wohlfühlatmosphäre für Sie und Ihn</li>
      </ul>
    </div>
    <div class="col-md-6">
      <h2>Wir bieten</h2>
      <ul class="list-unstyled">
        <li>Styling und Coloration - individuell auf Sie abgestimmt!</li>
        <li>Umforumg Ihres Haars</li>
        <li>Straight Therapie - Glättung des Haars</li>
        <li>Braut- und Hochzeitsfrisuren</li>
        <li>Steckfrisuren für jeden Anlass</li>
      </ul>
    </div>
  </div>
  <h2>Hairstyling und Trends</h2>
  <ul class="list-unstyled">
    <li>Tages- und Abendmakeup (<%= link_to "Pupa Makeup", "http://www.pupa-makeup.de", target: "_blank" %>)</li>
    <li><%= link_to "Great Lengths", "http://www.greatlengths.de", target: "_blank" %></li>
  </ul>

  <div class="row partner-images">
    <div class="col-md-4">
      <%= link_to image_tag("pupa.png",alt: "Pupa Makeup", class: "img-responsive"), "http://www.pupa-makeup.de", target: "_blank" %>
    </div>
    <div class="col-md-4">
      <%= link_to image_tag("pmlogo1blk.png",alt: "Paul Mitchell", class: "img-responsive"), "http://paul-mitchell.de", target: "_blank" %>
    </div>
    <div class="col-md-4">
      <%= link_to image_tag("gl-logo-de-cmyk.png",alt: "Great Lengths", class: "img-responsive"), "http://www.greatlengths.de", target: "_blank" %>
    </div>
  </div>

  <p class="lead">Entspannen Sie sich und genießen Sie die Verwöhnstunden bei uns. Wir freuen uns auf Sie!</p>
</div>

<script type="text/javascript">

    var tpj=jQuery;
    tpj.noConflict();

    tpj(document).ready(function() {

        if (tpj.fn.cssOriginal!=undefined)
            tpj.fn.css = tpj.fn.cssOriginal;

        var slider = tpj('.fullwidthbanner').revolution(
                {
                    delay:9000,
                    startwidth:960,
                    startheight:500,

                    onHoverStop:"on",						// Stop Banner Timet at Hover on Slide on/off

                    thumbWidth:100,							// Thumb With and Height and Amount (only if navigation Tyope set to thumb !)
                    thumbHeight:50,
                    thumbAmount:3,

                    hideThumbs:0,
                    navigationType:"bullet",				// bullet, thumb, none
                    navigationArrows:"solo",				// nexttobullets, solo (old name verticalcentered), none

                    navigationStyle:"round",				// round,square,navbar,round-old,square-old,navbar-old, or any from the list in the docu (choose between 50+ different item), custom


                    navigationHAlign:"center",				// Vertical Align top,center,bottom
                    navigationVAlign:"bottom",					// Horizontal Align left,center,right
                    navigationHOffset:0,
                    navigationVOffset:20,

                    soloArrowLeftHalign:"left",
                    soloArrowLeftValign:"center",
                    soloArrowLeftHOffset:20,
                    soloArrowLeftVOffset:0,

                    soloArrowRightHalign:"right",
                    soloArrowRightValign:"center",
                    soloArrowRightHOffset:20,
                    soloArrowRightVOffset:0,

                    touchenabled:"on",						// Enable Swipe Function : on/off



                    stopAtSlide:-1,							// Stop Timer if Slide "x" has been Reached. If stopAfterLoops set to 0, then it stops already in the first Loop at slide X which defined. -1 means do not stop at any slide. stopAfterLoops has no sinn in this case.
                    stopAfterLoops:-1,						// Stop Timer if All slides has been played "x" times. IT will stop at THe slide which is defined via stopAtSlide:x, if set to -1 slide never stop automatic

                    hideCaptionAtLimit:0,					// It Defines if a caption should be shown under a Screen Resolution ( Basod on The Width of Browser)
                    hideAllCaptionAtLilmit:0,				// Hide all The Captions if Width of Browser is less then this value
                    hideSliderAtLimit:0,					// Hide the whole slider, and stop also functions if Width of Browser is less than this value


                    fullWidth:"on",

                    shadow:0								//0 = no Shadow, 1,2,3 = 3 Different Art of Shadows -  (No Shadow in Fullwidth Version !)

                });
    });
</script>

app/views/home/team.html.erb
<% content_for(:title) do %>Team<% end %>
<div class="container container-panorama-header container-sidepages team">

</div>
<div class="container container-main">

  <div class="row padding-bottom">
    <div class="col-md-12">
      <h1 class="sidepages">Team <small>Das sind wir</small></h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 text-center">
      <%= image_tag("andrea.png",  class: "img-responsive team", alt: "Andrea") %>
      Andrea<br>Friseurmeisterin/Inhaberin
    </div>
    <div class="col-md-4 text-center">
      <%= image_tag("daniela.png", class: "img-responsive team", alt: "Daniela") %>
      Daniela<br>Friseurmeisterin
    </div>
    <div class="col-md-4 text-center">
      <%= image_tag("lisa.png", class: "img-responsive team", alt: "Lisa") %>
      Lisa<br>Friseurmeisterin
    </div>
  </div>

  <div class="row">
    <div class="col-md-4 text-center col-md-offset-2">
      <%= image_tag("christina.png", class: "img-responsive team", alt: "Christina") %>
      Christina<br>Gesellin in Teilzeit
    </div>

    <div class="col-md-4 text-center">
      <%= image_tag("inge.png", class: "img-responsive team", alt: "Inge") %>
      Inge<br>Gesellin in Teilzeit
    </div>
  </div>

  <p class="lead">Ihr Wohlbefinden und ihre Zufriedenheit sind unsere Motivation!</p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><% if content_for?(:title) %><%= content_for(:title) %> - <% end %>Kopfsache - Ihr Friseur in Stulln</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="Friseur Kopfsache, Ihr Friseur zum Wohlfühlen in Stulln. Wir bieten alles was Ihr Herz begehrt von Damen- und Herrenfrisuren über Tages- und Abendmakup bis hin zu Haarverlängerungen.">
  <meta name="keywords" content="Friseur Kopfsache, Friseur Stulln, Haarstyling Stulln, Haarverlängerung Stulln, Kopfsache Stulln, Frisör Kopfsache, Frisör Stulln, Haarschnitt">
  <meta name="author" content="Kopfsache Stulln">
  <meta name="google-site-verification" content="pFjQI8fSBaGhhVQr6EkrXcPoxQ0py1AN8xdPUu0kABE" />
  <%= stylesheet_link_tag    "application", media: "all" %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="icon" type="image/x-icon" href="/favicon.ico">
</head>
<body>

<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-65280258-1', 'auto');
    ga('send', 'pageview');

</script>

<div class="navbar navbar-default navbar-fixed-top navbar-extended">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("kopfsache-head-src.png") + "Kopfsache", root_path, :class => "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li <% if params[:action] == "salon" %>class="active"<% end %>><%= link_to "Salon", salon_path %></li>
        <li <% if params[:action] == "team" %>class="active"<% end %>><%= link_to "Team", team_path %></li>
        <%#<li><a href="#contact">Service</a></li> %>
        <li <% if params[:action] == "kontakt" %>class="active"<% end %>><%= link_to "Kontakt", kontakt_path %></li>
      </ul>
      <ul class="nav navbar-nav pull-right toolbar">
        <li class="hidden-md hidden-lg"><a href="tel:00499435300232"><i class="fa fa-phone"></i></a></li>
        <li class="facebook-link"><a href="https://www.facebook.com/KopfsacheStulln" target="facebook"><i class="fa fa-facebook-official"></i></a></li>
      </ul>
    </div>
  </div>
</div>


<%= yield %>


<div class="container footer text-right">
  <ul class="list-inline">
    <li>&copy; Kopfsache Stulln <%= Time.now.year %></li>
    <li><%= link_to "Impressum", impressum_path %></li>
  </ul>
</div>



</body>
</html>